//= error assert
//= stderr "assert failed\n3: foo(): 9\n2: call(String): 17\n1: main(): 5\n"

fn main() {
    std::call("foo");
}

fn foo() {
    assert(false);
}
